# Generated by Django 5.2.12 on 2026-04-03 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('specialization', models.CharField(max_length=255, verbose_name='Mutaxassislik')),
                ('work_start_time', models.TimeField(blank=True, null=True, verbose_name='Ish boshlanishi')),
                ('work_end_time', models.TimeField(blank=True, null=True, verbose_name='Ish tugashi')),
                ('work_days', models.JSONField(blank=True, default=list, verbose_name='Ish kunlari')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['-created_at'],
            },
        ),
    ]
