# Generated by Django 5.2.12 on 2026-04-03 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Davomiyligi (oy)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('monthly', 'Oylik'), ('full', "To'liq")], default='monthly', max_length=10, verbose_name="To'lov turi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
