# Generated by Django 5.2.12 on 2026-04-03 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('phone', 'Telefon'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('website', 'Veb-sayt'), ('referral', 'Tavsiya'), ('ad', 'Reklama'), ('walk_in', "O'zi kelgan"), ('other', 'Boshqa')], default='phone', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('trial_scheduled', 'Sinov darsi belgilandi'), ('enrolled', "Ro'yxatdan o'tdi"), ('cancelled', 'Bekor qilindi')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('course_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leadlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead tarixi',
                'verbose_name_plural': 'Lead tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
