# Generated by Django 5.2.12 on 2026-04-03 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lesson_days', models.JSONField(default=list)),
                ('lesson_start_time', models.TimeField()),
                ('lesson_end_time', models.TimeField()),
                ('status', models.CharField(choices=[('forming', 'Shakllanmoqda'), ('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='forming', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='courses.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teachers.teacher')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='groups.room')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('frozen', 'Muzlatilgan'), ('left', 'Chiqib ketgan'), ('graduated', 'Bitirgan')], default='active', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='students.student')),
            ],
            options={
                'verbose_name': 'Guruh talabasi',
                'verbose_name_plural': 'Guruh talabalari',
                'unique_together': {('group', 'student')},
            },
        ),
    ]
